import os 

NIGHTS_WATCH_TAG_NAME = '#NW'

NIGHTS_WATCH_ALARM_PREFIX = '#NW'

DEFAULT_METRICS = os.getenv('DEFAULT_METRICS', 'sys,ins,cpu,dsk')

NIGHTS_WATCH_SNS_LIST = os.getenv('NIGHTS_WATCH_SNS_LIST') 

