import os 

NIGHTS_WATCH_TAG_NAME = '#NW'

NIGHTS_WATCH_ALARM_PREFIX = '#NW'

DEFAULT_METRICS = os.getenv('DEFAULT_METRICS', 'sys,ins,cpu,dsk')

NIGHTS_WATCH_SNS_LIST = os.getenv('NIGHTS_WATCH_SNS_LIST') 

CPU_ALARM_THRESHOLD = os.getenv('CPU_ALARM_THRESHOLD', '97.0')
CPU_ALARM_PERIOD = os.getenv('CPU_ALARM_PERIOD', '300')

DISK_FULL_ALARM_THRESHOLD = os.getenv('DISK_FULL_ALARM_THRESHOLD', '90.0')
DISK_FULL_ALARM_PERIOD = os.getenv('DISK_FULL_ALARM_PERIOD', '900')

MEM_ALARM_THRESHOLD = os.getenv('MEM_ALARM_THRESHOLD', '90.0')
MEM_ALARM_PERIOD = os.getenv('MEM_ALARM_PERIOD', '900')
